### ISSUE TITLE
py4vasp.exceptions.exceptions.FileAccessError when trying to plot phonon_dos

### ISSUE THREAD

**Issue by henriquemiranda** [vasp-dev/py4vasp#53]
When trying to plot the phonon density of states with the following code:

```
import py4vasp
mycalc = py4vasp.Calculation.from_path( ".")
mycalc.phonon_band.plot()
mycalc.phonon_dos.plot()
```

I get the following error

```
Traceback (most recent call last):
  File "/Users/henrique/software/py4vasp/master/src/py4vasp/raw/_access.py", line 75, in _get_source
    return schema.sources[quantity][source]
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/henrique/software/workshop/phonons/e06_mgo2-dispersion/supercell_2x2x2/read.py", line 4, in <module>
    mycalc.phonon_dos.plot()
  File "/Users/henrique/software/py4vasp/master/src/py4vasp/data/_base.py", line 19, in func_with_access
    with self._data_context:
  File "/Users/henrique/software/py4vasp/master/src/py4vasp/data/_base.py", line 180, in __enter__
    self.data = self._stack.enter_context(context)
  File "/Users/henrique/miniconda3/lib/python3.9/contextlib.py", line 448, in enter_context
    result = _cm_type.__enter__(cm)
  File "/Users/henrique/miniconda3/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/Users/henrique/software/py4vasp/master/src/py4vasp/raw/_access.py", line 41, in _access
    yield state.access(quantity, source)
  File "/Users/henrique/software/py4vasp/master/src/py4vasp/raw/_access.py", line 64, in access
    source = self._get_source(quantity, source)
  File "/Users/henrique/software/py4vasp/master/src/py4vasp/raw/_access.py", line 82, in _get_source
    raise exception.FileAccessError(message)
py4vasp.exceptions.exceptions.FileAccessError: phonon_dos/default is not available in the HDF5 file. Please check the spelling of the arguments. Perhaps the version of py4vasp (0.4.0) is not up to date with the documentation.
```

The error is triggered only in mycalc.phonon_dos.plot()
I traced the problem down to the schema in src/py4vasp/raw/_definition.py
while `schema.add(raw.PhononBand,[...])` uses `name="default"`
`schema.add(raw.PhononDos,[...])` uses `name="phonon"`
if I change the latter to `name="default"` then it works.
I don't understand why because the error message above seems to indicate that it did not find the 'default' key in the schema.

This `FileAccessError` message should probably be re-worked because if it ever appears it is too difficult for the user to understand what is going on. It seems to be referring to variable names in the hdf5 file (or at least I assumed so) but I guess that's not the case.

**Comment by martin-schlipf** [comment]
Thanks for catching that, I will fix it today.
